on: 
  workflow_call:
    inputs:
      buildcache_key:
        type: string
        required: true

name: Common
env:
  CYPRESS_CACHE_FOLDER: ~/cypress-binary-cache

jobs:
  clear_cache:
    name: Clear Caches
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: |
          gh extension install actions/gh-actions-cache
          
          REPO=${{ github.repository }}
          BRANCH=${{ github.ref }}

          ## echo "Fetching list of cache key"
          ## cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
          cacheKeysForPR=(${{ inputs.buildcache_key }})

          ## Setting this to not fail the workflow while deleting cache keys. 
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  precache:
    name: Build and Cache
    needs: clear_cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      - uses: actions/cache@v4
        with:
          path: |
            ~/tmp_build
            ~/cypress-binary-cache
          key: ${{ inputs.buildcache_key }}
      - run: ls test
      # Bundle all 
      - run: npm run bootstrap
      - run: npm run bundle
      # Check bundlesize not exceeded
      - run: npm run bundlesize
      - run: pwd
      - run: sudo cp -r . ~/tmp_build
      - run: ls -l ~/tmp_build
