on: 
  push:
    tags:
      - 'v**'
  workflow_dispatch:
    inputs:
      buildAllPackages:
        type: boolean
        required: false
name: Release   
env:
  NPM_LUI_AUTH_TOKEN: ${{ secrets.NPM_LUI_AUTH_TOKEN }}

jobs:
  prepare: 
    uses: ./.github/workflows/prepare.yml
    secrets: inherit
    with:
      buildcache_key: buildcache-release-${{ github.ref }}

  publish:
    runs-on: ubuntu-latest
    needs: prepare
    if: github.repository == 'SAP/luigi'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      - uses: actions/cache@v4
        with:
          path: |
            ~/tmp_build
            ~/cypress-binary-cache
          key: buildcache-release-${{ github.ref }}
      - run: cp -r ~/tmp_build/* .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_LUI_AUTH_TOKEN" > ~/.npmrc
      - run: bash ./scripts/npmPublish.sh
